### PR TITLE
SSL and redirects

### PR DESCRIPTION
**Pull request by stefansundin**
- Support sending pingbacks to SSL servers.
- Support up to 3 redirects.

### CODE REVIEW

**Comment by stefansundin** [comment]
Actually, wait a few minutes, there is a small issue with this.

**Comment by stefansundin** [comment]
Okay, should be fixed now.

I have another issue that I have to use `request.body.read` instead of `request.body` inside `server.rb`. It actually worked a couple of times but now I can't get it to work again without changing that.

**Comment by stefansundin** [comment]
The biggest reasons to why I added redirect support is that many websites now use HSTS, so any pingbacks sent to `http://` will redirect to `https://`. Not accounting for this and other redirect reasons will cause many pingbacks to fail.

If you don't agree, then I can remove the redirect support and only keep the SSL support.

**Comment by AndreasWurm** [comment]
Thanks for taking the time to contribute your enhancements. Will have a detailed look later.

**Pull request closed without merging**
